### PR TITLE
atlantis test

### PR DESCRIPTION
**Pull request by jonpulsifer**

### CODE REVIEW

**Comment by jonpulsifer** [comment]
atlantis plan -d gcp/projects/kubesec

**Comment by j0npulsifer** [comment]
**Plan Error**
```
atlantis.yaml files not allowed because Atlantis is not running with --allow-repo-config
```

**Comment by jonpulsifer** [comment]
atlantis plan

**Comment by jonpulsifer** [comment]
atlantis plan

**Comment by j0npulsifer** [comment]
**Plan Error**
```
atlantis.yaml files not allowed because Atlantis is not running with --allow-repo-config
```

**Comment by jonpulsifer** [comment]
atlantis plan -d gcp/projects/kubesec

**Comment by j0npulsifer** [comment]
Ran Plan for dir: `gcp/projects/kubesec` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
exit status 1: running "sh -c terraform init -input=false -no-color" in "/home/atlantis/.atlantis/repos/jonpulsifer/cloudlab/1/default/gcp/projects/kubesec"
Initializing modules...
- module.gke
  Getting source "../../../terraform/modules/gke-beta-cluster"
- module.nodepool-containerd
  Getting source "../../../terraform/modules/gke-beta-nodepool"
- module.nodepool-shielded
  Getting source "../../../terraform/modules/gke-beta-nodepool"

Initializing the backend...

Successfully configured the backend "gcs"! Terraform will automatically
use this backend unless the backend configuration changes.
Error loading state: Failed to open state file at gs://kubesec/state/lab/default.tfstate: googleapi: got HTTP response code 403 with body: <?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>gke-nodes-cloudlab@kubesec.iam.gserviceaccount.com does not have storage.objects.get access to kubesec/state/lab/default.tfstate.</Details></Error>

```
</details>

**Comment by jonpulsifer** [comment]
atlantis plan

**Comment by j0npulsifer** [comment]
Ran Plan for 0 projects:

**Comment by jonpulsifer** [comment]
atlantis plan -d gcp/projects/kubesec

**Comment by j0npulsifer** [comment]
atlantis plan

**Comment by jonpulsifer** [comment]
atlantis plan

**Comment by j0npulsifer** [comment]
Ran Plan for 0 projects:

**Comment by jonpulsifer** [comment]
atlantis plan -d gcp/projects/kubesec

**Comment by j0npulsifer** [comment]
Ran Plan for dir: `gcp/projects/kubesec` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/usr/local/bin/terraform init -input=false -no-color -upgrade" in "/home/atlantis/.atlantis/repos/jonpulsifer/cloudlab/1/default/gcp/projects/kubesec": exit status 1
Upgrading modules...
- gke in ../../../terraform/modules/gke-beta-cluster
- nodepool-containerd in ../../../terraform/modules/gke-beta-nodepool
- nodepool-shielded in ../../../terraform/modules/gke-beta-nodepool

Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "kubernetes" (hashicorp/kubernetes) 1.11.1...

Provider "vault" v1.4.1 is not compatible with Terraform 0.12.24.

Provider version 2.0.0 is the earliest compatible version. Select it with 
the following version constraint:

	version = "~> 2.0"

Terraform checked all of the plugin versions matching the given constraint:
    ~> 1.4.1

Consult the documentation for this provider for more information on
compatibility between provider and Terraform versions.


Provider "google" v1.20.0 is not compatible with Terraform 0.12.24.

Provider version 2.5.0 is the earliest compatible version. Select it with 
the following version constraint:

	version = "~> 2.5"

Terraform checked all of the plugin versions matching the given constraint:
    ~> 1.20

Consult the documentation for this provider for more information on
compatibility between provider and Terraform versions.


Provider "google-beta" v1.20.0 is not compatible with Terraform 0.12.24.

Provider version 2.5.0 is the earliest compatible version. Select it with 
the following version constraint:

	version = "~> 2.5"

Terraform checked all of the plugin versions matching the given constraint:
    ~> 1.20

Consult the documentation for this provider for more information on
compatibility between provider and Terraform versions.


Warning: Skipping backend initialization pending configuration upgrade

The root module configuration contains errors that may be fixed by running the
configuration upgrade tool, so Terraform is skipping backend initialization.
See below for more information.


Error: incompatible provider version



Error: incompatible provider version



Error: incompatible provider version



```
</details>

**Comment by jonpulsifer** [comment]
atlantis plan -d gcp/projects/homelab-ng

**Comment by jonpulsifer** [comment]
atlantis plan -d gcp/projects/homelab-ng

**Comment by j0npulsifer** [comment]
Ran Plan for dir: `gcp/projects/homelab-ng` workspace: `default`

**Plan Error**
```
dir "gcp/projects/homelab-ng" does not exist
```

**Comment by jonpulsifer** [comment]
atlantis plan -d gcp/projects/homelab-ng

**Comment by j0npulsifer** [comment]
Ran Plan for dir: `gcp/projects/homelab-ng` workspace: `default`

**Plan Error**
```
running "/usr/local/bin/terraform init -input=false -no-color -upgrade" in "/home/atlantis/.atlantis/repos/jonpulsifer/cloudlab/1/default/gcp/projects/homelab-ng": exit status 1

Initializing the backend...

Successfully configured the backend "gcs"! Terraform will automatically
use this backend unless the backend configuration changes.

Error: Failed to get existing workspaces: querying Cloud Storage failed: googleapi: Error 403: seawall-ae-1234567@appspot.gserviceaccount.com does not have storage.objects.list access to kubesec., forbidden



```

**Comment by jonpulsifer** [comment]
atlantis plan -d gcp/projects/homelab-ng

**Comment by j0npulsifer** [comment]
Ran Plan for dir: `gcp/projects/homelab-ng` workspace: `default`

**Plan Error**
```
running "/usr/local/bin/terraform init -input=false -no-color -upgrade" in "/home/atlantis/.atlantis/repos/jonpulsifer/cloudlab/1/default/gcp/projects/homelab-ng": exit status 1

Initializing the backend...

Successfully configured the backend "gcs"! Terraform will automatically
use this backend unless the backend configuration changes.

Error: Failed to get existing workspaces: querying Cloud Storage failed: googleapi: Error 403: seawall-ae-1234567@appspot.gserviceaccount.com does not have storage.objects.list access to kubesec., forbidden



```

**Comment by jonpulsifer** [comment]
atlantis plan -d gcp/projects/homelab-ng

**Comment by j0npulsifer** [comment]
Ran Plan for dir: `gcp/projects/homelab-ng` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/usr/local/bin/terraform plan -input=false -refresh -no-color -out \"/home/atlantis/.atlantis/repos/jonpulsifer/cloudlab/1/default/gcp/projects/homelab-ng/default.tfplan\"" in "/home/atlantis/.atlantis/repos/jonpulsifer/cloudlab/1/default/gcp/projects/homelab-ng": exit status 1
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.google_client_config.current: Refreshing state...
google_service_account.datadog: Refreshing state... [id=projects/homelab-ng/serviceAccounts/datadog@homelab-ng.iam.gserviceaccount.com]
google_service_account.ddns: Refreshing state... [id=projects/homelab-ng/serviceAccounts/ddns-function@homelab-ng.iam.gserviceaccount.com]
data.google_iam_policy.gcs-homelab-ng: Refreshing state...
google_dns_managed_zone.home-pulsifer-ca: Refreshing state... [id=home-pulsifer-ca]
google_cloudfunctions_function.ddns: Refreshing state... [id=homelab-ng/us-east4/ddns]
google_project_organization_policy.allow_service_account_keys: Refreshing state... [id=homelab-ng:iam.disableServiceAccountKeyCreation]
google_project_organization_policy.allow_all_domains: Refreshing state... [id=homelab-ng:iam.allowedPolicyMemberDomains]
google_storage_bucket.homelab-ng: Refreshing state... [id=homelab-ng]
google_project_organization_policy.allow_production_services: Refreshing state... [id=homelab-ng:serviceuser.services]
google_project_organization_policy.allowed_locations: Refreshing state... [id=homelab-ng:constraints/gcp.resourceLocations]
google_project_organization_policy.allow_service_accounts: Refreshing state... [id=homelab-ng:iam.disableServiceAccountCreation]

Error: Error reading Organization policy for projects/homelab-ng: googleapi: Error 403: Cloud Resource Manager API has not been used in project 798779835577 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview?project=798779835577 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured



Error: Error reading DNSManagedZone "home-pulsifer-ca": googleapi: Error 403: Forbidden, forbidden



Error: Error reading Service Account "projects/homelab-ng/serviceAccounts/ddns-function@homelab-ng.iam.gserviceaccount.com": googleapi: Error 403: Permission iam.serviceAccounts.get is required to perform this operation on service account projects/homelab-ng/serviceAccounts/ddns-function@homelab-ng.iam.gserviceaccount.com., forbidden



Error: Error reading Storage Bucket "homelab-ng": googleapi: Error 400: Bucket is requester pays bucket but no user project provided., required



Error: Error reading Organization policy for projects/homelab-ng: googleapi: Error 403: Cloud Resource Manager API has not been used in project 798779835577 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview?project=798779835577 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured



Error: Error reading Organization policy for projects/homelab-ng: googleapi: Error 403: Cloud Resource Manager API has not been used in project 798779835577 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview?project=798779835577 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured



Error: Error reading Service Account "projects/homelab-ng/serviceAccounts/datadog@homelab-ng.iam.gserviceaccount.com": googleapi: Error 403: Permission iam.serviceAccounts.get is required to perform this operation on service account projects/homelab-ng/serviceAccounts/datadog@homelab-ng.iam.gserviceaccount.com., forbidden



Error: Error reading Organization policy for projects/homelab-ng: googleapi: Error 403: Cloud Resource Manager API has not been used in project 798779835577 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview?project=798779835577 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured



Error: Error reading Organization policy for projects/homelab-ng: googleapi: Error 403: Cloud Resource Manager API has not been used in project 798779835577 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview?project=798779835577 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured



Error: Error reading Target CloudFunctions Function "ddns": googleapi: Error 403: Permission 'cloudfunctions.functions.get' denied on resource 'projects/homelab-ng/locations/us-east4/functions/ddns' (or resource may not exist)., forbidden



```
</details>

**Comment by jonpulsifer** [comment]
atlantis plan -d gcp/projects/homelab-ng

**Comment by j0npulsifer** [comment]
Ran Plan for dir: `gcp/projects/homelab-ng` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/usr/local/bin/terraform plan -input=false -refresh -no-color -out \"/home/atlantis/.atlantis/repos/jonpulsifer/cloudlab/1/default/gcp/projects/homelab-ng/default.tfplan\"" in "/home/atlantis/.atlantis/repos/jonpulsifer/cloudlab/1/default/gcp/projects/homelab-ng": exit status 1
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

google_dns_managed_zone.home-pulsifer-ca: Refreshing state... [id=home-pulsifer-ca]
google_service_account.datadog: Refreshing state... [id=projects/homelab-ng/serviceAccounts/datadog@homelab-ng.iam.gserviceaccount.com]
google_service_account.ddns: Refreshing state... [id=projects/homelab-ng/serviceAccounts/ddns-function@homelab-ng.iam.gserviceaccount.com]
data.google_client_config.current: Refreshing state...
google_cloudfunctions_function.ddns: Refreshing state... [id=homelab-ng/us-east4/ddns]
data.google_iam_policy.gcs-homelab-ng: Refreshing state...
google_project_organization_policy.allow_service_account_keys: Refreshing state... [id=homelab-ng:iam.disableServiceAccountKeyCreation]
google_storage_bucket.homelab-ng: Refreshing state... [id=homelab-ng]
google_project_organization_policy.allow_service_accounts: Refreshing state... [id=homelab-ng:iam.disableServiceAccountCreation]
google_project_organization_policy.allowed_locations: Refreshing state... [id=homelab-ng:constraints/gcp.resourceLocations]
google_project_organization_policy.allow_production_services: Refreshing state... [id=homelab-ng:serviceuser.services]
google_project_organization_policy.allow_all_domains: Refreshing state... [id=homelab-ng:iam.allowedPolicyMemberDomains]
data.google_iam_policy.explicit: Refreshing state...
google_project_iam_policy.explicit: Refreshing state... [id=homelab-ng]

Error: Error reading Storage Bucket "homelab-ng": googleapi: Error 403: seawall-ae-1234567@appspot.gserviceaccount.com does not have storage.buckets.get access to homelab-ng., forbidden



```
</details>

**Comment by j0npulsifer** [comment]
Ran Plan for 7 projects:

1. dir: `gcp/projects/homelab-ng` workspace: `default`
1. dir: `gcp/projects/jonpulsifer` workspace: `default`
1. dir: `gcp/projects/kubesec` workspace: `default`
1. dir: `gcp/projects/trusted-builds` workspace: `default`
1. dir: `gcp/projects/wishlist-4362e` workspace: `default`
1. dir: `gcp/resource-manager` workspace: `default`
1. dir: `vault` workspace: `default`

### 1. dir: `gcp/projects/homelab-ng` workspace: `default`
**Plan Error**
<details><summary>Show Output</summary>

```
running "/usr/local/bin/terraform plan -input=false -refresh -no-color -out \"/home/atlantis/.atlantis/repos/jonpulsifer/cloudlab/1/default/gcp/projects/homelab-ng/default.tfplan\"" in "/home/atlantis/.atlantis/repos/jonpulsifer/cloudlab/1/default/gcp/projects/homelab-ng": exit status 1
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

google_dns_managed_zone.home-pulsifer-ca: Refreshing state... [id=home-pulsifer-ca]
google_cloudfunctions_function.ddns: Refreshing state... [id=homelab-ng/us-east4/ddns]
data.google_client_config.current: Refreshing state...
google_service_account.datadog: Refreshing state... [id=projects/homelab-ng/serviceAccounts/datadog@homelab-ng.iam.gserviceaccount.com]
google_service_account.ddns: Refreshing state... [id=projects/homelab-ng/serviceAccounts/ddns-function@homelab-ng.iam.gserviceaccount.com]
data.google_iam_policy.gcs-homelab-ng: Refreshing state...
google_project_organization_policy.allow_service_accounts: Refreshing state... [id=homelab-ng:iam.disableServiceAccountCreation]
google_project_organization_policy.allow_all_domains: Refreshing state... [id=homelab-ng:iam.allowedPolicyMemberDomains]
google_project_organization_policy.allow_service_account_keys: Refreshing state... [id=homelab-ng:iam.disableServiceAccountKeyCreation]
google_storage_bucket.homelab-ng: Refreshing state... [id=homelab-ng]
google_project_organization_policy.allowed_locations: Refreshing state... [id=homelab-ng:constraints/gcp.resourceLocations]
google_project_organization_policy.allow_production_services: Refreshing state... [id=homelab-ng:serviceuser.services]
data.google_iam_policy.explicit: Refreshing state...
google_project_iam_policy.explicit: Refreshing state... [id=homelab-ng]

Error: Error reading Storage Bucket "homelab-ng": googleapi: Error 403: seawall-ae-1234567@appspot.gserviceaccount.com does not have storage.buckets.get access to homelab-ng., forbidden



```
</details>

---
### 2. dir: `gcp/projects/jonpulsifer` workspace: `default`
**Plan Error**
<details><summary>Show Output</summary>

```
running "/usr/local/bin/terraform plan -input=false -refresh -no-color -out \"/home/atlantis/.atlantis/repos/jonpulsifer/cloudlab/1/default/gcp/projects/jonpulsifer/default.tfplan\"" in "/home/atlantis/.atlantis/repos/jonpulsifer/cloudlab/1/default/gcp/projects/jonpulsifer": exit status 1
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.google_client_config.current: Refreshing state...
data.google_iam_policy.explicit: Refreshing state...
google_project_service.project: Refreshing state... [id=jonpulsifer/sourcerepo.googleapis.com]
google_sourcerepo_repository.dotfiles: Refreshing state... [id=jonpulsifer/dotfiles]
data.google_iam_policy.gcs-jonpulsifer: Refreshing state...
google_project_iam_policy.explicit: Refreshing state... [id=jonpulsifer]
google_storage_bucket.jonpulsifer: Refreshing state... [id=jonpulsifer]

Error: Error reading Storage Bucket "jonpulsifer": googleapi: Error 403: seawall-ae-1234567@appspot.gserviceaccount.com does not have storage.buckets.get access to jonpulsifer., forbidden



Error: Error reading Project Service jonpulsifer/sourcerepo.googleapis.com: Batch "project/jonpulsifer/services" for request "List Project Services jonpulsifer" returned error: Failed to list enabled services for project jonpulsifer: googleapi: Error 403: Service Usage API has not been used in project 798779835577 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/serviceusage.googleapis.com/overview?project=798779835577 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured



```
</details>

---
### 3. dir: `gcp/projects/kubesec` workspace: `default`
**Plan Error**
<details><summary>Show Output</summary>

```
running "/usr/local/bin/terraform init -input=false -no-color -upgrade" in "/home/atlantis/.atlantis/repos/jonpulsifer/cloudlab/1/default/gcp/projects/kubesec": exit status 1
Upgrading modules...
- lab in 
- network in 

Error: Unreadable module directory

Unable to evaluate directory symlink: lstat ../../../../terraform-modules: no
such file or directory


Error: Failed to read module directory

Module directory  does not exist or cannot be read.


Error: Unreadable module directory

Unable to evaluate directory symlink: lstat ../../../../terraform-modules: no
such file or directory


Error: Failed to read module directory

Module directory  does not exist or cannot be read.


Error: Unreadable module directory

Unable to evaluate directory symlink: lstat ../../../../terraform-modules: no
such file or directory


Error: Failed to read module directory

Module directory  does not exist or cannot be read.


Error: Unreadable module directory

Unable to evaluate directory symlink: lstat ../../../../terraform-modules: no
such file or directory


Error: Failed to read module directory

Module directory  does not exist or cannot be read.


Error: Unreadable module directory

Unable to evaluate directory symlink: lstat ../../../../terraform-modules: no
such file or directory


Error: Failed to read module directory

Module directory  does not exist or cannot be read.


```
</details>

---
### 4. dir: `gcp/projects/trusted-builds` workspace: `default`
**Plan Error**
```
running "/usr/local/bin/terraform init -input=false -no-color -upgrade" in "/home/atlantis/.atlantis/repos/jonpulsifer/cloudlab/1/default/gcp/projects/trusted-builds": exit status 1
Upgrading modules...
Downloading github.com/jonpulsifer/terraform-modules for network...
- network in .terraform/modules/network/gce-vpc

Initializing the backend...

Successfully configured the backend "gcs"! Terraform will automatically
use this backend unless the backend configuration changes.
Error loading state: Failed to open state file at gs://kubesec/trusted-builds/default.tfstate: googleapi: got HTTP response code 400 with body: <?xml version='1.0' encoding='UTF-8'?><Error><Code>ResourceIsEncryptedWithCustomerEncryptionKey</Code><Message>The resource is encrypted with a customer encryption key.</Message><Details>The requested object is encrypted by a customer-supplied encryption key.</Details></Error>

```

---
### 5. dir: `gcp/projects/wishlist-4362e` workspace: `default`
<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # google_dns_managed_zone.wishlist-app will be created
+ resource "google_dns_managed_zone" "wishlist-app" {
      + description  = "Domain for the wishlist app"
      + dns_name     = "wishin.app."
      + id           = (known after apply)
      + labels       = {
          + "domain"      = "wishlist-app"
          + "environment" = "production"
        }
      + name         = "wishlist-app"
      + name_servers = (known after apply)
      + project      = (known after apply)
      + visibility   = "public"
    }

  # google_project_iam_member.cert-manager will be created
+ resource "google_project_iam_member" "cert-manager" {
      + etag    = (known after apply)
      + id      = (known after apply)
      + member  = "serviceAccount:cert-manager@kubesec.iam.gserviceaccount.com"
      + project = (known after apply)
      + role    = "roles/dns.admin"
    }

  # google_project_iam_member.external-dns will be created
+ resource "google_project_iam_member" "external-dns" {
      + etag    = (known after apply)
      + id      = (known after apply)
      + member  = "serviceAccount:external-dns@kubesec.iam.gserviceaccount.com"
      + project = (known after apply)
      + role    = "roles/dns.admin"
    }

  # google_project_organization_policy.allow_production_services will be created
+ resource "google_project_organization_policy" "allow_production_services" {
      + constraint  = "serviceuser.services"
      + etag        = (known after apply)
      + id          = (known after apply)
      + project     = "wishlist-4362e"
      + update_time = (known after apply)
      + version     = (known after apply)

      + list_policy {
          + suggested_value = (known after apply)

          + allow {
              + all = true
            }
        }
    }

  # google_project_organization_policy.allow_service_accounts will be created
+ resource "google_project_organization_policy" "allow_service_accounts" {
      + constraint  = "iam.disableServiceAccountCreation"
      + etag        = (known after apply)
      + id          = (known after apply)
      + project     = "wishlist-4362e"
      + update_time = (known after apply)
      + version     = (known after apply)

      + boolean_policy {
          + enforced = false
        }
    }

  # google_project_service.clouddns will be created
+ resource "google_project_service" "clouddns" {
      + disable_dependent_services = true
      + disable_on_destroy         = true
      + id                         = (known after apply)
      + project                    = (known after apply)
      + service                    = "dns.googleapis.com"
    }

  # google_service_account.wishlist will be created
+ resource "google_service_account" "wishlist" {
      + account_id   = "wishlist"
      + display_name = "Application service account"
      + email        = (known after apply)
      + id           = (known after apply)
      + name         = (known after apply)
      + project      = (known after apply)
      + unique_id    = (known after apply)
    }

  # google_service_account_iam_member.wishlist-workload-identity will be created
+ resource "google_service_account_iam_member" "wishlist-workload-identity" {
      + etag               = (known after apply)
      + id                 = (known after apply)
      + member             = "serviceAccount:kubesec.svc.id.goog[wishlist/wishlist]"
      + role               = "roles/iam.workloadIdentityUser"
      + service_account_id = (known after apply)
    }

Plan: 8 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d gcp/projects/wishlist-4362e`
* :put_litter_in_its_place: To **delete** this plan click [here](http://21fe6e196cd2:8080/lock?id=jonpulsifer%252Fcloudlab%252Fgcp%252Fprojects%252Fwishlist-4362e%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d gcp/projects/wishlist-4362e`
</details>

---
### 6. dir: `gcp/resource-manager` workspace: `default`
**Plan Error**
<details><summary>Show Output</summary>

```
running "/usr/local/bin/terraform plan -input=false -refresh -no-color -out \"/home/atlantis/.atlantis/repos/jonpulsifer/cloudlab/1/default/gcp/resource-manager/default.tfplan\"" in "/home/atlantis/.atlantis/repos/jonpulsifer/cloudlab/1/default/gcp/resource-manager": exit status 1
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.google_organization.org: Refreshing state...
data.google_billing_account.cloudlab: Refreshing state...

Error: Error reading billing accounts: googleapi: Error 403: Cloud Billing API has not been used in project 798779835577 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudbilling.googleapis.com/overview?project=798779835577 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured

  on billing.tf line 1, in data "google_billing_account" "cloudlab":
   1: data "google_billing_account" "cloudlab" {



Error: Organization not found: pulsifer.ca

  on organization.tf line 1, in data "google_organization" "org":
   1: data "google_organization" "org" {



```
</details>

---
### 7. dir: `vault` workspace: `default`
**Plan Error**
<details><summary>Show Output</summary>

```
running "/usr/local/bin/terraform init -input=false -no-color -upgrade" in "/home/atlantis/.atlantis/repos/jonpulsifer/cloudlab/1/default/vault": exit status 1

Initializing the backend...

Successfully configured the backend "gcs"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Checking for available provider plugins...

Provider "vault" v1.9.0 is not compatible with Terraform 0.12.24.

Provider version 2.0.0 is the earliest compatible version. Select it with 
the following version constraint:

	version = "~> 2.0"

Terraform checked all of the plugin versions matching the given constraint:
    ~> 1.8

Consult the documentation for this provider for more information on
compatibility between provider and Terraform versions.


Error: incompatible provider version



```
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by jonpulsifer** [comment]
atlantis plan -d gcp/projects/homelab-ng

**Comment by jonpulsifer** [comment]
atlantis plan -d gcp/projects/homelab-ng

**Comment by j0npulsifer** [comment]
Ran Plan for dir: `gcp/projects/homelab-ng` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/usr/local/bin/terraform plan -input=false -refresh -no-color -out \"/home/atlantis/.atlantis/repos/jonpulsifer/cloudlab/1/default/gcp/projects/homelab-ng/default.tfplan\"" in "/home/atlantis/.atlantis/repos/jonpulsifer/cloudlab/1/default/gcp/projects/homelab-ng": exit status 1
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

google_cloudfunctions_function.ddns: Refreshing state... [id=homelab-ng/us-east4/ddns]
data.google_client_config.current: Refreshing state...
google_service_account.ddns: Refreshing state... [id=projects/homelab-ng/serviceAccounts/ddns-function@homelab-ng.iam.gserviceaccount.com]
google_service_account.datadog: Refreshing state... [id=projects/homelab-ng/serviceAccounts/datadog@homelab-ng.iam.gserviceaccount.com]
google_dns_managed_zone.home-pulsifer-ca: Refreshing state... [id=home-pulsifer-ca]
data.google_iam_policy.gcs-homelab-ng: Refreshing state...
google_project_organization_policy.allowed_locations: Refreshing state... [id=homelab-ng:constraints/gcp.resourceLocations]
google_storage_bucket.homelab-ng: Refreshing state... [id=homelab-ng]
google_project_organization_policy.allow_all_domains: Refreshing state... [id=homelab-ng:iam.allowedPolicyMemberDomains]
google_project_organization_policy.allow_service_accounts: Refreshing state... [id=homelab-ng:iam.disableServiceAccountCreation]
google_project_organization_policy.allow_service_account_keys: Refreshing state... [id=homelab-ng:iam.disableServiceAccountKeyCreation]
google_project_organization_policy.allow_production_services: Refreshing state... [id=homelab-ng:serviceuser.services]
data.google_iam_policy.explicit: Refreshing state...
google_project_iam_policy.explicit: Refreshing state... [id=homelab-ng]

Error: Error reading Storage Bucket "homelab-ng": googleapi: Error 403: seawall-ae-1234567@appspot.gserviceaccount.com does not have storage.buckets.get access to homelab-ng., forbidden



Error: Error reading Organization policy for projects/homelab-ng: googleapi: Error 403: Cloud Resource Manager API has not been used in project 798779835577 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview?project=798779835577 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured



```
</details>

**Comment by jonpulsifer** [comment]
atlantis plan -d gcp/projects/homelab-ng

**Comment by j0npulsifer** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `gcp/projects/wishlist-4362e` workspace: `default`

**Pull request merged**
