### PR TITLE
Add alice to storage

### PR DESCRIPTION
**Pull request by jonpulsifer**
Signed-off-by: Jonathan Pulsifer <jonathan.pulsifer@shopify.com>

### CODE REVIEW

**Comment by j0npulsifer** [comment]
Ran Plan for dir: `gcp/projects/kubesec` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/usr/local/bin/terraform init -input=false -no-color -upgrade" in "/home/atlantis/.atlantis/repos/jonpulsifer/cloudlab/13/default/gcp/projects/kubesec": exit status 1
Upgrading modules...
- lab in 
- network in 

Error: Unreadable module directory

Unable to evaluate directory symlink: lstat ../../../../terraform-modules: no
such file or directory


Error: Failed to read module directory

Module directory  does not exist or cannot be read.


Error: Unreadable module directory

Unable to evaluate directory symlink: lstat ../../../../terraform-modules: no
such file or directory


Error: Failed to read module directory

Module directory  does not exist or cannot be read.


Error: Unreadable module directory

Unable to evaluate directory symlink: lstat ../../../../terraform-modules: no
such file or directory


Error: Failed to read module directory

Module directory  does not exist or cannot be read.


Error: Unreadable module directory

Unable to evaluate directory symlink: lstat ../../../../terraform-modules: no
such file or directory


Error: Failed to read module directory

Module directory  does not exist or cannot be read.


Error: Unreadable module directory

Unable to evaluate directory symlink: lstat ../../../../terraform-modules: no
such file or directory


Error: Failed to read module directory

Module directory  does not exist or cannot be read.


```
</details>

**Comment by j0npulsifer** [comment]
Ran Plan for dir: `gcp/projects/kubesec` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
~ update in-place

Terraform will perform the following actions:

  # google_storage_bucket_iam_policy.gcs-cloud-lab will be updated in-place
~ resource "google_storage_bucket_iam_policy" "gcs-cloud-lab" {
        bucket      = "b/cloud-lab"
        etag        = "CB4="
        id          = "cloud-lab"
      ~ policy_data = jsonencode(
          ~ {
              ~ bindings = [
                  ~ {
                      ~ members = [
                            "group:cloud@pulsifer.ca",
                            "serviceAccount:821879192255@cloudbuild.gserviceaccount.com",
                          + "user:alice@pulsifer.ca",
                        ]
                        role    = "roles/storage.admin"
                    },
                ]
            }
        )
    }

Plan: 0 to add, 1 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d gcp/projects/kubesec`
* :put_litter_in_its_place: To **delete** this plan click [here](http://5ed2b0e59da0:8080/lock?id=jonpulsifer%252Fcloudlab%252Fgcp%252Fprojects%252Fkubesec%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d gcp/projects/kubesec`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by jonpulsifer** [comment]
atlantis apply

**Comment by jonpulsifer** [comment]
atlantis apply

**Comment by j0npulsifer** [comment]
Ran Apply for dir: `gcp/projects/kubesec` workspace: `default`

```diff
google_storage_bucket_iam_policy.gcs-cloud-lab: Modifying... [id=cloud-lab]
google_storage_bucket_iam_policy.gcs-cloud-lab: Modifications complete after 1s [id=cloud-lab]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

```

**Comment by j0npulsifer** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by j0npulsifer** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `gcp/projects/kubesec` workspace: `default`

**Pull request merged**
